# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-10-05 19:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psiApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomersName',
            fields=[
                ('customerName', models.CharField(max_length=300)),
                ('auto_increment_id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Proactive',
            fields=[
                ('Tasks', models.CharField(max_length=200)),
                ('Month', models.CharField(max_length=200)),
                ('Date', models.CharField(max_length=200)),
                ('CheckedBy', models.CharField(max_length=200)),
                ('Status', models.CharField(max_length=200)),
                ('Notes', models.CharField(max_length=200)),
                ('Customer_id', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('auto_increment_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    #    migrations.DeleteModel(
    #        name='CustomersTableNew',
    #    ),
    #    migrations.DeleteModel(
    #        name='Logtables1',
    #    ),
    ]
